version: '3.8'

services:
  # GoFr SSE Server
  sse-server:
    build: ./server
    container_name: sse-status-server
    ports:
      - "8000:8000"  # GoFr server
      - "8001:8001"  # SSE endpoint
      - "2121:2121"  # Metrics
    restart: unless-stopped
    networks:
      - sse-network
    environment:
      - GOFR_TELEMETRY=false
      - PORT=8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/sse-info"]
      interval: 30s
      timeout: 10s
      retries: 3

  # React + D3.js Client
  sse-client:
    build: ./client
    container_name: sse-status-client
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - sse-network
    depends_on:
      - sse-server
    environment:
      - REACT_APP_SSE_URL=http://localhost:8001
      - REACT_APP_API_URL=http://localhost:8000

networks:
  sse-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  sse-data: